### PR TITLE
Pricing styling

### PR DESCRIPTION
**Pull request by paddyohanlon**
Screenshot 2024-08-23 at 20 14 05

### CODE REVIEW

**Comment by saschat** [comment]
I think we need to separate personal from organizational plans and add sliders for different sizes. Let's talk about that on Monday.

**Comment by paddyohanlon** [comment]
Effective communication commit:
localhost_4322_effective-communication_

**Comment by saschat** [comment]
Beautiful :-)

Two suggestions (I will refrain from nitpicking small stuff, we can do that later):
* Somehow visually separate the sections. Not sure how. Maybe if the heading + first paragraph is left aligned? Similar to the homepage.
* Lets organize "own your burden a bit. It basically has an intro (larger) then some rules and then a note about efficiency. Lets put efficiency before rules and maybe also put each in a box with a title?

**Comment by paddyohanlon** [comment]
The async column content is now all the same width, grouping it better visually. And burden is now wider, and visually distinct because of the new card column. Written communication is the same as async, so you get a nice narrow-wide-narrow layout, which separates the sections nicely I think.

I've also tweaked the styles in places, increasing heading size in places for example.

localhost_4322_effective-communication_ (1)

**Comment by saschat** [comment]
looks good. Do you want to update the pricing page in this PR too or merge and do it later?

**Comment by paddyohanlon** [comment]
I'll do pricing in this PR

**Comment by paddyohanlon** [comment]
Screenshot 2024-08-30 at 10 06 20

**Review by saschat — APPROVED** [review]
Great.

Note, there are two conflicts:

1. The base is now gone
2. I emphasized "asynchronous communication" in the hero which you moved.

**Comment by paddyohanlon** [comment]
The early access sign up.
Screenshot 2024-09-04 at 16 54 05

**Pull request merged**
